export const CONFIG = {
    ENV: process.env.ENV,
    PORT: process.env.PORT,
    DATABASE_SERVER_URL: process.env.DATABASE_SERVER_URL,
    BASE_DB_NAME: process.env.BASE_DB_NAME,
    GET_DATABASE_CONNECTION_URL: (): string => CONFIG.DATABASE_SERVER_URL + CONFIG.BASE_DB_NAME,
    JWT_SECRET: process.env.JWT_SECRET,
    CLIENT_BASE_DOMAIN_FOR_APPS: process.env.CLIENT_BASE_DOMAIN_FOR_APPS,
};
